server:
  port: 4000
#spring:
#  datasource:
#    url: jdbc:h2:./devdb
#  jpa:
#    hibernate:
#      ddl-auto: update
spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none